# Generated by Django 2.1.7 on 2019-07-12 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_forgetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 12, 42, 50, 143178)),
        ),
    ]
