# Generated by Django 2.1.7 on 2019-07-13 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190712_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 11, 53, 34, 279411)),
        ),
    ]
