# Generated by Django 2.1.7 on 2019-05-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
